<a href="https://colab.research.google.com/github/LatiefDataVisionary/pm-tools-absa-analysis/blob/main/notebook/absa_x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. Import libraries**

In [16]:
import pandas as pd

## **2. Load Data dan Inspect Awal**

In [17]:
trello_df = pd.read_csv('https://raw.githubusercontent.com/LatiefDataVisionary/pm-tools-absa-analysis/refs/heads/main/data/raw/x/trello_x_reviews.csv')
jira_df = pd.read_csv('https://raw.githubusercontent.com/LatiefDataVisionary/pm-tools-absa-analysis/refs/heads/main/data/raw/x/jira_x_reviews.csv')
clickup_df = pd.read_csv('https://raw.githubusercontent.com/LatiefDataVisionary/pm-tools-absa-analysis/refs/heads/main/data/raw/x/clickup_x_reviews.csv')

In [18]:
trello_df.head(10)

,timestamp,text,target_keyword
0,2026-04-23T18:23:51.000Z,A little over 1 week since officially launched...,@trello
1,2026-04-23T11:52:00.000Z,You could also consider http:// ProofHub.com ...,@trello
2,2026-04-22T18:06:14.000Z,First open source project collboration of our ...,@trello
3,2026-04-22T18:00:49.000Z,"The wait is finally over. Project ""Noobieteam""...",@trello
4,2026-04-22T06:32:39.000Z,Strategy isn't a ladder; it's an ecosystem. ...,@trello
5,2026-04-21T13:50:55.000Z,Most @trello users don’t know you can now se...,@trello
6,2026-04-19T14:30:20.000Z,I have over 200 vinyls of all genres that I'm ...,@trello
7,2026-04-19T13:54:27.000Z,"ok, now i'm ready to ditch @OpenAI , @canva ...",@trello
8,2026-04-19T04:00:01.000Z,Professionalizing Your Startup: Building a Hig...,@trello
9,2026-04-18T20:03:10.000Z,from @DPGAlliance you can find a countless n...,@trello

In [19]:
jira_df.head(10)

,timestamp,text,target_keyword
0,2026-04-25T08:00:32.000Z,DEVOPS LAYERS PLANNING LAYER → Defines projec...,@jira OR jira OR #jira
1,2026-04-22T11:40:22.000Z,Your company's knowledge is trapped. It's sca...,@jira OR jira OR #jira
2,2026-04-25T11:58:41.000Z,( ◜ϖ◝ ).;:…( ◜ϖ◝ ...:.;::..( ◜;::: .:.;:...,@jira OR jira OR #jira
3,2026-04-20T14:32:04.000Z,New policy from @Atlassian : Unless you opt...,@jira OR jira OR #jira
4,2026-04-25T12:33:11.000Z,NaN,@jira OR jira OR #jira
5,2026-04-25T12:23:29.000Z,はじめまして、りにゃと申します ぜひ繋がっていただければ嬉しいです！ フォロー失礼します,@jira OR jira OR #jira
6,2026-04-13T18:38:53.000Z,"Yeah, there is, but he forbade it.",@jira OR jira OR #jira
7,2026-04-25T09:00:30.000Z,AREWA24 Taku ce! Tamu ce!! Ta kowa ce!!! Ta Ja...,@jira OR jira OR #jira
8,2026-04-25T12:02:39.000Z,すごいドラマチック勝利 気持ちいいくらい勝ちましたねー おつかれさまでした,@jira OR jira OR #jira
9,2026-04-25T12:12:06.000Z,[ 2026. 04. 25 ] 7.00 PM Current Followers :...,@jira OR jira OR #jira

In [20]:
clickup_df.head(10)

,timestamp,text,target_keyword
0,2026-04-17T13:57:24.000Z,I just saw ClickUp launch AI agents that work ...,@clickup OR clickup OR #clickup
1,2026-04-23T13:00:37.000Z,AI Tools Ecosystem ┃ ┣ Time Management ┃ ┣ A...,@clickup OR clickup OR #clickup
2,2026-04-10T09:20:00.000Z,The biggest problem with clickup is that it al...,@clickup OR clickup OR #clickup
3,2026-04-15T16:39:13.000Z,I built a custom agent inside my @clickup wo...,@clickup OR clickup OR #clickup
4,2026-03-26T16:24:25.000Z,Top AI Productivity Tools You MUST Try in 2026...,@clickup OR clickup OR #clickup
5,2026-04-22T16:28:18.000Z,ClickUp is slowly becoming an everything app.,@clickup OR clickup OR #clickup
6,2026-04-17T08:17:27.000Z,I got millions of views last week. And my Cli...,@clickup OR clickup OR #clickup
7,2026-04-18T07:49:32.000Z,ClickUp Super Agents are wild. You can litera...,@clickup OR clickup OR #clickup
8,2026-04-05T14:56:38.000Z,Hizi hapa tools 5 za kupanga kazi na ratiba za...,@clickup OR clickup OR #clickup
9,2026-04-17T12:20:34.000Z,Plane : un outil de gestion de projet Open Sou...,@clickup OR clickup OR #clickup

In [21]:
trello_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       285 non-null    object
 1   text            284 non-null    object
 2   target_keyword  285 non-null    object
dtypes: object(3)
memory usage: 6.8+ KB

In [22]:
jira_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       249 non-null    object
 1   text            248 non-null    object
 2   target_keyword  249 non-null    object
dtypes: object(3)
memory usage: 6.0+ KB

In [23]:
clickup_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       166 non-null    object
 1   text            165 non-null    object
 2   target_keyword  166 non-null    object
dtypes: object(3)
memory usage: 4.0+ KB

In [25]:
dataframes = {
    "trello_df": trello_df,
    "jira_df": jira_df,
    "clickup_df": clickup_df
}

for df_name, df in dataframes.items():
    print(f"--- Null Information for {df_name} ---")
    null_counts = df.isnull().sum()
    null_percentages = (null_counts / len(df)) * 100

    null_info_df = pd.DataFrame({
        'Null Count': null_counts,
        'Null Percentage': null_percentages.round(2)
    })
    print(null_info_df)
    print("\n")

--- Null Information for trello_df ---
                Null Count  Null Percentage
timestamp                0             0.00
text                     1             0.35
target_keyword           0             0.00


--- Null Information for jira_df ---
                Null Count  Null Percentage
timestamp                0              0.0
text                     1              0.4
target_keyword           0              0.0


--- Null Information for clickup_df ---
                Null Count  Null Percentage
timestamp                0              0.0
text                     1              0.6
target_keyword           0              0.0

In [26]:
for df_name, df in dataframes.items():
    print(f"--- Duplicates Information for {df_name} ---")
    duplicate_counts = df.duplicated().sum()
    print(duplicate_counts)
    print("\n")

--- Duplicates Information for trello_df ---
0


--- Duplicates Information for jira_df ---
0


--- Duplicates Information for clickup_df ---
0

## **3. Data Cleaning - Handling Missing Values**

In [ ]:
for df_name, df in dataframes.items():
    initial_rows = len(df)
    df.dropna(subset=['text'], inplace=True)
    final_rows = len(df)
    print(f"--- {df_name} Null Value Handling ---")
    print(f"Initial rows: {initial_rows}")
    print(f"Rows after dropping nulls in 'text': {final_rows}")
    print(f"Number of rows dropped: {initial_rows - final_rows}")
    print("\n")

# Update the dataframes dictionary with cleaned dataframes
trello_df = dataframes['trello_df']
jira_df = dataframes['jira_df']
clickup_df = dataframes['clickup_df']

In [ ]:
for df_name, df in dataframes.items():
    print(f"--- Null Information after cleaning for {df_name} ---")
    null_counts = df.isnull().sum()
    null_percentages = (null_counts / len(df)) * 100

    null_info_df = pd.DataFrame({
        'Null Count': null_counts,
        'Null Percentage': null_percentages.round(2)
    })
    print(null_info_df)
    print("\n")